import json
from flask import Flask, Response, request, jsonify
from marshmallow import Schema, fields, ValidationError
from web3 import Web3

class CreateUserSchema(Schema):
    userId = fields.String(required=True)
    name = fields.String(required=True)
    score = fields.Integer(required=True)

class GetUserSchema(Schema):
    userId = fields.String(required=True)


def connectWeb3():
    w3=Web3(Web3.HTTPProvider("http://ganachecli:8545"))
    w3.eth.defaultAccount = w3.eth.accounts[0]
    print("Connect")
    return w3

def connectCreditScore(w3):
    with open("./resources/CreditScore.json", 'r') as f:
        datastore = json.load(f)
    abi = datastore["abi"]
    #You must use "w3.toChecksumAddress()", if your address is generated by test-node(like "Ganache"...etc)
    contract_address = w3.toChecksumAddress(datastore["contract_address"])
    # Create the contract instance with the newly-deployed address
    creditScore = w3.eth.contract(
        address=contract_address, abi=abi,
    )
    return creditScore

app = Flask(__name__)
@app.route("/blockchain/create", methods=['POST'])
def createUser():
    # Web3Providerに接続
    w3=connectWeb3()
    # コントラクト情報取得
    creditScore = connectCreditScore(w3)
    # リクエスト情報取得
    body = request.get_json()
    result, error = CreateUserSchema().load(body)
    if error:
        return jsonify(error), 422 
    tx_hash = creditScore.functions.createUser(result['userId'],result['name'],result['score']).transact()
    # Wait for transaction to be mined...
    receipt = w3.eth.waitForTransactionReceipt(tx_hash)
    # 作成結果取得
    user=creditScore.functions.getUser(result['userId']).call()
    return jsonify({"user": user}), 200

@app.route("/blockchain/get", methods=['POST'])
def getUser():
    # Web3Providerに接続
    w3=connectWeb3()
    # コントラクト情報取得
    creditScore = connectCreditScore(w3)
    # リクエスト情報取得
    body = request.get_json()
    result, error = GetUserSchema().load(body)
    if error:
        return jsonify(error), 422 
    user=creditScore.functions.getUser(result['userId']).call()
    return jsonify({"user": user}), 200
